// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEQpnP8ahx0wY36o41rYLSzKBtAu1zLA',
    appId: '1:451617534775:web:29659c09af4a9b806320b2',
    messagingSenderId: '451617534775',
    projectId: 'trackactive-24a90',
    authDomain: 'trackactive-24a90.firebaseapp.com',
    storageBucket: 'trackactive-24a90.firebasestorage.app',
    measurementId: 'G-75R8C8NQ47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVP1dC5cilnxQwU8N5qPqbhqQB5GLnAZk',
    appId: '1:451617534775:android:58d83efba131361f6320b2',
    messagingSenderId: '451617534775',
    projectId: 'trackactive-24a90',
    storageBucket: 'trackactive-24a90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jwHHdUR5BcVy6YOe-AlyELoshvraAA4',
    appId: '1:451617534775:ios:06cea348526326a36320b2',
    messagingSenderId: '451617534775',
    projectId: 'trackactive-24a90',
    storageBucket: 'trackactive-24a90.firebasestorage.app',
    iosBundleId: 'com.example.trackactive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6jwHHdUR5BcVy6YOe-AlyELoshvraAA4',
    appId: '1:451617534775:ios:06cea348526326a36320b2',
    messagingSenderId: '451617534775',
    projectId: 'trackactive-24a90',
    storageBucket: 'trackactive-24a90.firebasestorage.app',
    iosBundleId: 'com.example.trackactive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEQpnP8ahx0wY36o41rYLSzKBtAu1zLA',
    appId: '1:451617534775:web:7e9f620715d03f146320b2',
    messagingSenderId: '451617534775',
    projectId: 'trackactive-24a90',
    authDomain: 'trackactive-24a90.firebaseapp.com',
    storageBucket: 'trackactive-24a90.firebasestorage.app',
    measurementId: 'G-1P7TK1JE73',
  );
}
